import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import clsx from 'clsx'
import Menu from '@components/header/Menu'
import Navbar from '@components/common/Navbar'
const Home: NextPage = () => {

 
  return (
    // className={clsx('container')}
    <div  > 
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
       <main className={styles.main}>
          <Menu />
      </main> 
    
    </div>
  )
}

export default Home
